---
- name: Mkdirs and copy files
  hosts: elastic
  become: yes
  tasks:

    - name: Create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /home/freddy/configs
        - /home/freddy/docker_volumes/elasticsearch
        - /home/freddy/configs/elasticsearch
        - /home/freddy/configs/filebeat
        - /home/freddy/configs/kibana
        - /home/freddy/configs/logstash
        - /home/freddy/configs/logstash/pipelines

    - name: Copy docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: /home/freddy/docker-compose.yml

    - name: Copy elasticsearch config
      copy:
        src: ./configs/elasticsearch/config.yml
        dest: /home/freddy/configs/elasticsearch/config.yml

    - name: Copy filebeat config
      copy:
        src: ./configs/filebeat/config.yml
        dest: /home/freddy/configs/filebeat/config.yml

    - name: Copy kibana config
      copy:
        src: ./configs/kibana/config.yml
        dest: /home/freddy/configs/kibana/config.yml

    - name: Copy logstash config
      copy:
        src: ./configs/logstash/config.yml
        dest: /home/freddy/configs/logstash/config.yml

    - name: Copy logstash pipelines config
      copy:
        src: ./configs/logstash/pipelines/service_stamped_json_logs.conf
        dest: /home/freddy/configs/logstash/pipelines/service_stamped_json_logs.conf

    - name: Copy logstash pipelines.yml
      copy:
        src: ./configs/logstash/pipelines.yml
        dest: /home/freddy/configs/logstash/pipelines.yml

    - name: Update apt and install prerequisites
      apt:
        update_cache: yes
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Create Docker keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      ansible.builtin.command:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

    - name: Set permissions on Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker APT repository
      ansible.builtin.shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Make docker-compose.yml executable
      file:
        path: /home/freddy/docker-compose.yml
        mode: '0755'

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Set permissions for Nginx log file
      file:
        path: /var/log/nginx/access.log
        mode: '0777'

    - name: Check Nginx status
      ansible.builtin.shell: curl localhost
      register: nginx_status

    - name: Output Nginx status
      debug:
        msg: "{{ nginx_status.stdout }}"

    - name: Start Docker Compose
      ansible.builtin.command:
        cmd: docker compose -f /home/freddy/docker-compose.yml up -d
