services:
  kibana:
    image: kibana:7.16.1
    volumes:
      - ./configs/kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elk
    ports:
      - "5601:5601"
    # environment:
    #   - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
    #   - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    # env_file:
    #   - ./secrets.env

networks:
  elk:
    driver: bridge
