---
- name: Install Zabbix Server
  hosts: zabbix
  become: yes

  vars_files:
    - zabbix_secrets.yml

  roles:
    - role: community.zabbix.zabbix_server
      vars:
        zabbix_server_version: 6.0
        zabbix_server_database: mysql
        zabbix_server_database_long: mysql
        zabbix_server_name: "{{ zabbix_name }}"
        zabbix_server_dbhost: "localhost"
        zabbix_server_dbname: "{{ zabbix_dbname }}"
        zabbix_server_dbuser: "{{ zabbix_dbuser }}"
        zabbix_server_dbpassword: "{{ zabbix_dbpassword }}"
        zabbix_server_dbport: 3306
        zabbix_server_listenport: 10051
  # tasks:
  #   - name: Repo PHP 7.4
  #     apt_repository:
  #       repo: ppa:ondrej/php

  #   - name: Updating the repo
  #     apt:
  #       update_cache: yes

  #   - name: Install PHP 7.4 and required extensions
  #     apt:
  #       name: "{{ item }}"
  #       state: present
  #     loop:
  #       - php7.4-fpm
  #       - php7.4-bcmath
  #       - php7.4-mbstring
  #       - php7.4-common
  #       - php7.4-sockets
  #       - php7.4-gd
  #       - php7.4-xml
  #       - php7.4-xmlwriter
  #       - php7.4-xmlreader
  #       - php7.4-ctype
  #       - php7.4-gettext

  #   - name: Uninstall php8
  #     apt:
  #       name: "php8*"
  #       state: absent
